export const INIT_CURRENCY = 'INIT_CURRENCY';
export const ADD_CURRENCY = 'ADD_CURRENCY';
export const DELETE_CURRENCY = 'DELETE_CURRENCY';
export const DRAG_CURRENCY = 'DRAG_CURRENCY';
export const ERROR_CURRENCY = 'ERROR_CURRENCY'; 
export const UPDATE_CURRENCY = 'UPDATE_CURRENCY'; 

export default {
    INIT_CURRENCY,
    ADD_CURRENCY,
    DELETE_CURRENCY,
    DRAG_CURRENCY,
    ERROR_CURRENCY,
    UPDATE_CURRENCY
}